# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-06 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notes',
            fields=[
                ('n_id', models.AutoField(primary_key=True, serialize=False)),
                ('n_name', models.CharField(max_length=20)),
                ('n_owner', models.CharField(max_length=20)),
                ('n_content', models.CharField(max_length=100)),
            ],
        ),
    ]
