# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-07 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserMgnt', '0002_notes_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='mark_complete',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
