# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-07 07:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserMgnt', '0002_notes_owner_id'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shared_notes',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('n_shrd_name', models.CharField(max_length=20)),
                ('n_shrd_with', models.CharField(max_length=20)),
                ('n_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserMgnt.notes')),
                ('n_shrd_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
