# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-08 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_shared_notes_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shared_notes',
            name='s_mark_complete',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
