# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-08 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_shared_notes_s_mark_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shared_notes',
            old_name='s_mark_complete',
            new_name='mark_complete',
        ),
    ]
